### ISSUE TITLE
Resposta ao teste 1 2013

### ISSUE THREAD

**Issue by filipedeluna** [jmg-duarte/cp-tests#1]
https://github.com/jmg-duarte/cp-tests/blob/b55ca85da5d1eee7af3c2c91948596bbc692eb3f/t1-13-14/question-1.tex#L22

Não compreendo como poderá ser possível este x = 4.

Bom trabalho e obrigado pela partilha destes docs para o teste.

**Comment by jmg-duarte** [comment]
Estive a refazer os interleavings, o `x` não pode ser 3 nem 4, o que depois leva ao `z` não poder ser 6 ou 7.
Fixed pelo https://github.com/jmg-duarte/cp-tests/commit/541e3038b94217988c951a6d4525eb142bd348f4
