### ISSUE TITLE
Question 11

### ISSUE THREAD

**Issue by filipedeluna** [jmg-duarte/cp-tests#12]
https://github.com/jmg-duarte/cp-tests/blob/bef08921c7d08230d6556795d254a3cc8814551f/sample/main.tex#L29

It's B. RAR's do not.

**Comment by jmg-duarte** [comment]
RAR's are not a dependecy, furthermore the question is which DO NOT affect correctness.

**Comment by jffp113** [comment]
I agree with Jose. I had B but after thinking RAR it’s independent

**Comment by filipedeluna** [comment]
Makes sense, I thought RARs counted, even though they technically do not cause data dependencies.

Still, B and D basically say the same thing.

All except all DO NOT affect -> all affect
All do -> all affect.

Might be a language problem.

**Comment by jmg-duarte** [comment]
B does not say the same thing.
You still have control dependency https://en.wikipedia.org/wiki/Data_dependency

**Comment by filipedeluna** [comment]
> B does not say the same thing.
> You still have control dependency https://en.wikipedia.org/wiki/Data_dependency

You're right! Thanks! Since this wasn't covered in the slides/classes, I dindn't know about it.
