### ISSUE TITLE
Sample test question 26

### ISSUE THREAD

**Issue by filipedeluna** [jmg-duarte/cp-tests#13]
https://github.com/jmg-duarte/cp-tests/blob/541e3038b94217988c951a6d4525eb142bd348f4/sample/main.tex#L65

Don't we need to prove there is a common correlation for a high-level data race to exist? How do we go about doing this?

**Comment by jmg-duarte** [comment]
That is covered in Piazza

**Comment by filipedeluna** [comment]
Thanks!
