### ISSUE TITLE
Question  27

### ISSUE THREAD

**Issue by filipedeluna** [jmg-duarte/cp-tests#14]
https://github.com/jmg-duarte/cp-tests/blob/541e3038b94217988c951a6d4525eb142bd348f4/sample/main.tex#L87

Shouldn't it be C? 

From the slides:
![image](https://user-images.githubusercontent.com/26190639/85474770-066d0880-b5ad-11ea-8d75-2c3a8e1b2a7a.png)

**Comment by jmg-duarte** [comment]
Yes. I have a question about it but had no time to address it.
Feel free to add a new pr

A terça, 23 de jun de 2020, 23:55, Filipe de Luna <notifications@github.com>
escreveu:

**Comment by filipedeluna** [comment]
Maybe tomorrow. Good luck buddy!
