### ISSUE TITLE
Valor errado?

### ISSUE THREAD

**Issue by filipedeluna** [jmg-duarte/cp-tests#5]
https://github.com/jmg-duarte/cp-tests/blob/541e3038b94217988c951a6d4525eb142bd348f4/t2-15-16/main.tex#L40

Aqui só consegui obter: 3, 5, 6. Não consigo obter o 4.

**Comment by jmg-duarte** [comment]
First and foremost, next time please share your resolution as well.
You can in fact get three with the following interleaving:
```
m1 reads r1 = 0
m2 completes fully
m1 writes r1 + 1
m1 completes the rest
```
This way `x` ends at 3.
Validate this with your solution so I can update the document.

For 4 you have:
| T1 | T2 |
| --- | --- |
| `read 0` | |
| `write 1` | |
| | `read 1`|
| `read 1` | |
| `write 2`| |
| | `write 3` |
| `read 3` | |
| | ... |
| `write 4` | |

With ... representing the other iterations of the loop.

**Comment by filipedeluna** [comment]
Thanks! I'll share my solution next time. The table method is great

**Comment by filipedeluna** [comment]
Do you want me to create PRs? or would you rather edit yourself?

**Comment by jmg-duarte** [comment]
If you want/don't mind feel free to do so!

A terça, 23 de jun de 2020, 19:45, Filipe de Luna <notifications@github.com>
escreveu:
