### ISSUE TITLE
Missing atomic

### ISSUE THREAD

**Issue by filipedeluna** [jmg-duarte/cp-tests#6]
https://github.com/jmg-duarte/cp-tests/blob/541e3038b94217988c951a6d4525eb142bd348f4/t2-15-16/main.tex#L45

This solution does not have into account "y=3" is atomic.

So it needs to be completely remade.

| T1 | T2 | T3 |  | T1 | T2 | T3 |  | T1 | T2 | T3 |  | T1 | T2 | T3 |
|-|-|-|-|-|-|-|-|-|-|:-:|-|-|-|-|
| read x=0 |  |  |  | read x=0 |  |  |  |  read x=0 |  |  |  |  read x=0 |  |  |
|  | read y=0 |  |  |  | read y=0 |  |  |  |  |  write y=3 |  |  |  |  write y=3 |
|  | write y=1 |  |  |  | write y=1 |  |  |  |  read y=3 |  |  |  |  read y=3 |  |
|  |  | write y=3 |  |  |  | write y=3 |  |  |  write y=4 |  |  |  |  write y=4 |  |
|  |  | read y=3 |  | write x=1 |  |  |  |  |  |  read y=4 |  |  |  |   read y=4 |
|  |  | write x=4 |  |  |  | read y=3 |  |  |  |  write x=5 |  |  write x=1 |  |  |
| write x=1 |  |  |  |  |  | write x=4 |  |  write x=1 |  |  |  |  |  |   write x=2 |

| T1 | T2 | T3 |  | T1 | T2 | T3 |  | T1 | T2 | T3 |  | T1 | T2 | T3 |
|-|-|-|-|-|-|-|-|-|-|:-:|-|-|-|-|
|  | read y=0 |  |  |  |  | write y=3 |  |  |  |  |  |  |  |  |
|  | write y=1 |  |  |  | read y=3 |  |  |  |  |  |  |  |  |  |
|  |  | write y=3 |  |  | write y=4 |  |  |  |  |  |  |  |  |  |
|  |  | read y=3 |  |  |  | read y=4 |  |  |  |  |  |  |  |  |
|  |  | write x=4 |  |  |  | write x=5 |  |  |  |  |  |  |  |  |
| read x=4 |  |  |  |  read x=5 |  |  |  |  |  |  |  |  |  |  |
| write x=5 |  |  |  |  write x=6 |  |  |  |  |  |  |  |  |  |  |

X = 1,2,4,5,6
Y = 3,4
(X,Y) = (1,3), (1,4), (2,4), (4,3), (6,4), (5,3)

**Comment by filipedeluna** [comment]
i think that's it?

**Comment by jmg-duarte** [comment]
I'm not understanding the context, can you specify?

**Comment by filipedeluna** [comment]
"Knowing that the execution keeps the relative order of the instructions (i.e. in M3, ‘y=3’ is always executed
before ‘x=y+1’) and that the assignment is executed atomically, list all the final possible values for the
variables 'x', ‘y’, and for the pairs ‘(x,y)’ at the end of the execution of M1, M2 and M3."

Doesn't this mean "y=3" is executed atomically?

**Comment by filipedeluna** [comment]
Guess I might have misread. Just noticed the parentheses around the "i.e.".

**Comment by filipedeluna** [comment]
Does he mean the "writes" are all atomic but not the "reads"?

**Comment by jmg-duarte** [comment]
The read is a single instruction and in the case of y=3 the same applies.
In my notes I considered y=3 to be a single instruction so I'm confused to what I may have missed

**Comment by filipedeluna** [comment]
"the assignment is executed atomically" - I don't understand this.. I figured he meant the "y = 3"

**Comment by jmg-duarte** [comment]
This is kinda confusing so I'll leave it as is until a better look is taken
