### ISSUE TITLE
6 15-16

### ISSUE THREAD

**Issue by filipedeluna** [jmg-duarte/cp-tests#9]
https://github.com/jmg-duarte/cp-tests/blob/541e3038b94217988c951a6d4525eb142bd348f4/t2-15-16/main.tex#L75

If only two threads deadlock or livelock, shouldn't a third, doing a completely different computation, be able to progress?

If all threads do a simultaneous compare&swap, it will fail for all, I think. That's why you need to add backoffs.

Also, what is busy-waiting?

Thanks again for taking the time to help everyone out.

**Comment by jmg-duarte** [comment]
If two lock and you have more threads they will indeed progress (if they are independent).
About the C&S I have no idea...
Busy-waiting is essentially a `while(true){}` which can't be suspended. See https://en.wikipedia.org/wiki/Busy_waiting

**Comment by filipedeluna** [comment]
> If two lock and you have more threads they will indeed progress (if they are independent).
> About the C&S I have no idea...
> Busy-waiting is essentially a `while(true){}` which can't be suspended. See https://en.wikipedia.org/wiki/Busy_waiting

I implemented my own CAS in the first practical class. If you don't add a backoff, they'll just keep noticing the value changed and will never progress.

https://en.wikipedia.org/wiki/Compare-and-swap
"researchers have found that total system performance can be improved in multiprocessor systems—where many threads constantly update some particular shared variable—if threads that see their CAS fail use exponential backoff—in other words, wait a little before retrying the CAS."

Also:
https://stackoverflow.com/questions/52337878/why-are-cas-not-considered-equivalent-to-busy-waiting-loops

Contention would be absurd if all of them constantly and synchronously try to do the operation. It might take a very long time until one can finally do the operation fast enough.

**Comment by jmg-duarte** [comment]
Uh thank you! 
I'm learning a lot today.
If you don't mind submitting a PR and reference it here, please do so. 
It would be very appreciated.
